services:
  redirect-bot:
    build: .
    container_name: telegram-redirect-bot
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Монтируем только .env для возможности изменения настроек без пересборки
      - ./.env:/app/.env:ro

